# [DESIGN 1] Execute your favorite apps at launch
exec-once = LOCALE_ARCHIVE=/usr/lib/locale/locale-archive waybar & swaybg -i ~/dotfiles/Wallpapers/Wallpapers/alena-aenami-far-from-tomorrow.jpg -m fill &

# Wofi config location
env = WOFI_CONF,.config/wofi/config
env = WOFI_STYLE,.config/wofi/style.css

# Cursor themes
env = XDG_CURRENT_DESKTOP,sway
env = XCURSOR_THEME,Bibata-Modern-Classic
env = XCURSOR_SIZE,22
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,22

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 5
    
    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = true
	      new_optimizations = true
    }

     blurls = waybar
     inactive_opacity = 0.7

     drop_shadow = false
     shadow_range = 4
     shadow_render_power = 3
     col.shadow = rgba(1a1a1aee)
}


