# Windows XP design
exec-once = LOCALE_ARCHIVE=/usr/lib/locale/locale-archive waybar -c ~/.config/waybar/xp.jsonc -s ~/.config/waybar/xp.css & swaybg -i ~/dotfiles/Wallpapers/Wallpapers/xp.jpg -m fill &

$WOFI_CONF = .config/wofi/xp
$WOFI_STYLE = .config/wofi/style.css
$KITTY_OPTS = -o background_opacity=0.9

layerrule = noanim, wofi

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 5
    
    blur {
        enabled = false
        size = 6
        passes = 3
        ignore_opacity = false
	      new_optimizations = true
    }

     blurls = waybar
     inactive_opacity = 0.9

     drop_shadow = true
     shadow_range = 4
     shadow_render_power = 3
     col.shadow = rgba(1a1a1aee)
}


